DROP TABLE IF EXISTS processes;
DROP TABLE IF EXISTS documentation_entries;
DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS children;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS kita_masterdata;
